project_name: local-pvc-cleaner
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

kos:
  - repositories:
      - quay.io/drangon/local-pvc-cleaner
    tags:
      - "{{.Tag}}"
      - latest
    bare: true
    base_image: alpine
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

release:
  disable: true
